repos:
  - repo: local
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff lint
        entry: uv run ruff check
        language: system
      # Run the formatter.
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system


  - repo: https://github.com/commitizen-tools/commitizen
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
    rev: v3.13.0


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
